# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pc\Desktop\KOD\örnek\Görsel Programlama Vize Proje\Restoran_Otomasyonu\admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminPanel(object):
    def setupUi(self, AdminPanel):
        AdminPanel.setObjectName("AdminPanel")
        AdminPanel.resize(1280, 800)
        AdminPanel.setStyleSheet("QMainWindow {\n"
" background-color: #ECEFF1; /* Açık Beyaz */\n"
" border-radius: 15px; /* QMainWindow\'a doğrudan border-radius uygulamak pencere yöneticisine bağlı olarak çalışmayabilir */\n"
" border: 2px solid #303F9F; /* Koyu Lacivert */\n"
"}\n"
"QFrame#sideMenuFrame {\n"
" background-color: #3F51B5; /* Orta Lacivert */\n"
" border: none;\n"
"}\n"
"QListWidget {\n"
" background-color: transparent;\n"
" border: none;\n"
" color: #ECEFF1; /* Açık Beyaz */\n"
"}\n"
"QListWidget::item {\n"
" padding: 12px;\n"
" border-bottom: 1px solid #5C6BC0; /* Açıkça Ayıran Lacivert */\n"
"}\n"
"QListWidget::item:hover {\n"
" background-color: #5C6BC0; /* Açıkça Ayıran Lacivert */\n"
"}\n"
"QListWidget::item:selected {\n"
" background-color: #283593; /* Daha Koyu Lacivert */\n"
"}\n"
"QPushButton {\n"
" background-color: #3F51B5; /* Orta Lacivert */\n"
" color: #ECEFF1; /* Açık Beyaz */\n"
" border-radius: 8px;\n"
" padding: 8px 16px;\n"
" font-weight: bold;\n"
" border: 2px solid #3F51B5;\n"
" min-width: 80px; /* Mevcut buton stilini korudum */\n"
"}\n"
"QPushButton:hover {\n"
" background-color: #5C6BC0; /* Açıkça Ayıran Lacivert */\n"
" border: 2px solid #5C6BC0;\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: #303F9F; /* Koyu Lacivert */\n"
" border: 2px solid #303F9F;\n"
"}\n"
"QTableWidget {\n"
" background-color: #ECEFF1; /* Açık Beyaz */\n"
" alternate-background-color: #F5F5F5; /* Daha Açık Beyaz */\n"
" selection-background-color: #283593; /* Daha Koyu Lacivert */\n"
" selection-color: #ECEFF1; /* Açık Beyaz */\n"
" border: 1px solid #303F9F; /* Koyu Lacivert */\n"
" border-radius: 5px;\n"
" margin: 5px;\n"
"}\n"
"QHeaderView::section {\n"
" background-color: #303F9F; /* Koyu Lacivert */\n"
" color: #ECEFF1; /* Açık Beyaz */\n"
" padding: 5px;\n"
" font-weight: bold;\n"
" border: none;\n"
" border-bottom: 2px solid #3F51B5; /* Orta Lacivert */\n"
"}\n"
"QLabel {\n"
" color: #303F9F; /* Koyu Lacivert */\n"
"}\n"
"QLineEdit {\n"
" background-color: #F5F5F5; /* Daha Açık Beyaz */\n"
" border: 1px solid #3F51B5; /* Orta Lacivert */\n"
" border-radius: 5px;\n"
" padding: 5px;\n"
" margin: 5px;\n"
" color: #303F9F; /* Koyu Lacivert */\n"
"}\n"
"QComboBox {\n"
" background-color: #F5F5F5; /* Daha Açık Beyaz */\n"
" border: 1px solid #3F51B5; /* Orta Lacivert */\n"
" border-radius: 5px;\n"
" padding: 5px;\n"
" margin: 5px;\n"
" color: #303F9F; /* Koyu Lacivert */\n"
"}\n"
"QComboBox::drop-down {\n"
" subcontrol-origin: padding;\n"
" subcontrol-position: top right;\n"
" width: 20px;\n"
" border-left-width: 1px;\n"
" border-left-color: #5C6BC0; /* Açıkça Ayıran Lacivert */\n"
" border-left-style: solid; /* just a single line */\n"
" border-top-right-radius: 3px;\n"
" border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
" /* image: url(:/icons/down_arrow.png); Eğer böyle bir ikonunuz varsa */\n"
" width: 12px;\n"
" height: 12px;\n"
" color: #303F9F; /* İkon rengi olarak lacivert */\n"
"}\n"
"QTabWidget::pane { /* The tab widget frame */\n"
" border: 1px solid #3F51B5; /* Orta Lacivert */\n"
" background: #ECEFF1; /* Açık Beyaz */\n"
" border-radius: 5px;\n"
" margin: 5px;\n"
"}\n"
"QTabWidget::tab-bar:top {\n"
" alignment: center;\n"
"}\n"
"QTabBar::tab {\n"
" background: #5C6BC0; /* Açıkça Ayıran Lacivert */\n"
" color: #ECEFF1; /* Açık Beyaz */\n"
" border: 1px solid #3F51B5; /* Orta Lacivert */\n"
" padding: 8px 15px;\n"
" border-top-left-radius: 5px;\n"
" border-top-right-radius: 5px;\n"
" margin-right: 2px;\n"
" font-weight: bold;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
" background: #3F51B5; /* Orta Lacivert */\n"
" color: #ECEFF1; /* Açık Beyaz */\n"
"}\n"
"QStatusBar {\n"
" background-color: #ECEFF1; /* Açık Beyaz */\n"
" color: #303F9F; /* Koyu Lacivert */\n"
" padding: 3px;\n"
" border-top: 2px solid #3F51B5; /* Orta Lacivert */\n"
" border-radius: 0;\n"
"}\n"
"QLabel#label_restaurantName {\n"
" color: #ECEFF1; /* Açık Beyaz */\n"
" border-bottom: 2px solid #5C6BC0; /* Açıkça Ayıran Lacivert */\n"
"}\n"
"QLabel#label_customerTitle, QLabel#label_menuTitle, QLabel#label_financeTitle, QLabel#label_ordersTitle {\n"
" color: #3F51B5; /* Orta Lacivert */\n"
" font-weight: bold;\n"
" border-bottom: 2px solid #5C6BC0; /* Açıkça Ayıran Lacivert */\n"
" padding-bottom: 7px;\n"
" margin-bottom: 10px;\n"
"}\n"
"QLabel#lblTotalIncome, QLabel#lblTotalExpenses, QLabel#lblNetProfit {\n"
" color: #3F51B5; /* Orta Lacivert */\n"
" font-weight: bold;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(AdminPanel)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.sideMenuFrame = QtWidgets.QFrame(self.centralwidget)
        self.sideMenuFrame.setMinimumWidth(220)
        self.sideMenuFrame.setMaximumWidth(220)
        self.sideMenuFrame.setObjectName("sideMenuFrame")
        self.sideMenuLayout = QtWidgets.QVBoxLayout(self.sideMenuFrame)
        self.sideMenuLayout.setObjectName("sideMenuLayout")
        self.label_restaurantName = QtWidgets.QLabel(self.sideMenuFrame)
        self.label_restaurantName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_restaurantName.setStyleSheet("\n"
"           font-size: 20px;\n"
"           font-weight: bold;\n"
"           color: #ECEFF1;\n"
"           padding: 20px 0;\n"
"           border-bottom: 2px solid #5C6BC0;\n"
"          ")
        self.label_restaurantName.setObjectName("label_restaurantName")
        self.sideMenuLayout.addWidget(self.label_restaurantName)
        self.listWidget_menu = QtWidgets.QListWidget(self.sideMenuFrame)
        self.listWidget_menu.setIconSize(QtCore.QSize(24, 24))
        self.listWidget_menu.setStyleSheet("\n"
"           background-color: transparent;\n"
"           border: none;\n"
"           color: #ECEFF1; /* Menü metin rengi */\n"
"          ")
        self.listWidget_menu.setObjectName("listWidget_menu")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/customer_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/menu_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/finance_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/orders_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget_menu.addItem(item)
        self.sideMenuLayout.addWidget(self.listWidget_menu)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.sideMenuLayout.addItem(spacerItem)
        self.btnLogout = QtWidgets.QPushButton(self.sideMenuFrame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/logout_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogout.setIcon(icon4)
        self.btnLogout.setStyleSheet("\n"
"           QPushButton {\n"
"            background-color: #283593; /* Daha Koyu Lacivert */\n"
"            color: #ECEFF1;\n"
"            border-radius: 8px;\n"
"            padding: 10px 16px;\n"
"            font-weight: bold;\n"
"            border: 2px solid #283593;\n"
"           }\n"
"\n"
"           QPushButton:hover {\n"
"            background-color: #3F51B5; /* Orta Lacivert */\n"
"            border: 2px solid #3F51B5;\n"
"           }\n"
"\n"
"           QPushButton:pressed {\n"
"            background-color: #1A237E; /* En Koyu Lacivert */\n"
"            border: 2px solid #1A237E;\n"
"           }\n"
"          ")
        self.btnLogout.setObjectName("btnLogout")
        self.sideMenuLayout.addWidget(self.btnLogout)
        self.mainLayout.addWidget(self.sideMenuFrame)
        self.stackedWidget_content = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_content.setObjectName("stackedWidget_content")
        self.customerPage = QtWidgets.QWidget()
        self.customerPage.setObjectName("customerPage")
        self.customerLayout = QtWidgets.QVBoxLayout(self.customerPage)
        self.customerLayout.setObjectName("customerLayout")
        self.label_customerTitle = QtWidgets.QLabel(self.customerPage)
        self.label_customerTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_customerTitle.setStyleSheet("\n"
"            font-size: 24px;\n"
"            font-weight: bold;\n"
"            padding: 15px;\n"
"            color: #3F51B5;\n"
"            border-bottom: 2px solid #5C6BC0;\n"
"            margin-bottom: 10px;\n"
"           ")
        self.label_customerTitle.setObjectName("label_customerTitle")
        self.customerLayout.addWidget(self.label_customerTitle)
        self.customerTable = QtWidgets.QTableWidget(self.customerPage)
        self.customerTable.setColumnCount(5)
        self.customerTable.setRowCount(0)
        self.customerTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.customerTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.customerTable.setShowGrid(True)
        self.customerTable.setStyleSheet("\n"
"            background-color: #ECEFF1;\n"
"            alternate-background-color: #F5F5F5;\n"
"            selection-background-color: #283593;\n"
"            selection-color: #ECEFF1;\n"
"            border: 1px solid #303F9F;\n"
"            border-radius: 5px;\n"
"            margin: 5px;\n"
"           ")
        self.customerTable.setObjectName("customerTable")
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(4, item)
        self.customerLayout.addWidget(self.customerTable)
        self.customerButtonLayout = QtWidgets.QHBoxLayout()
        self.customerButtonLayout.setObjectName("customerButtonLayout")
        self.btnAddCustomer = QtWidgets.QPushButton(self.customerPage)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/add_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddCustomer.setIcon(icon5)
        self.btnAddCustomer.setStyleSheet("\n"
"              QPushButton {\n"
"               background-color: #3F51B5;\n"
"               color: #ECEFF1;\n"
"               border-radius: 8px;\n"
"               padding: 8px 16px;\n"
"               font-weight: bold;\n"
"               border: 2px solid #3F51B5;\n"
"              }\n"
"\n"
"              QPushButton:hover {\n"
"               background-color: #5C6BC0;\n"
"               border: 2px solid #5C6BC0;\n"
"              }\n"
"\n"
"              QPushButton:pressed {\n"
"               background-color: #303F9F;\n"
"               border: 2px solid #303F9F;\n"
"              }\n"
"             ")
        self.btnAddCustomer.setObjectName("btnAddCustomer")
        self.customerButtonLayout.addWidget(self.btnAddCustomer)
        self.btnEditCustomer = QtWidgets.QPushButton(self.customerPage)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/edit_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditCustomer.setIcon(icon6)
        self.btnEditCustomer.setStyleSheet("\n"
"              QPushButton {\n"
"               background-color: #3F51B5;\n"
"               color: #ECEFF1;\n"
"               border-radius: 8px;\n"
"               padding: 8px 16px;\n"
"               font-weight: bold;\n"
"               border: 2px solid #3\n"
"               border: 2px solid #3F51B5;\n"
"              }\n"
"\n"
"              QPushButton:hover {\n"
"               background-color: #5C6BC0;\n"
"               border: 2px solid #5C6BC0;\n"
"              }\n"
"\n"
"              QPushButton:pressed {\n"
"               background-color: #303F9F;\n"
"               border: 2px solid #303F9F;\n"
"              }\n"
"             ")
        self.btnEditCustomer.setObjectName("btnEditCustomer")
        self.customerButtonLayout.addWidget(self.btnEditCustomer)
        self.btnDeleteCustomer = QtWidgets.QPushButton(self.customerPage)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/delete_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeleteCustomer.setIcon(icon7)
        self.btnDeleteCustomer.setStyleSheet("\n"
"              QPushButton {\n"
"               background-color: #3F51B5;\n"
"               color: #ECEFF1;\n"
"               border-radius: 8px;\n"
"               padding: 8px 16px;\n"
"               font-weight: bold;\n"
"               border: 2px solid #3F51B5;\n"
"              }\n"
"\n"
"              QPushButton:hover {\n"
"               background-color: #5C6BC0;\n"
"               border: 2px solid #5C6BC0;\n"
"              }\n"
"\n"
"              QPushButton:pressed {\n"
"               background-color: #303F9F;\n"
"               border: 2px solid #303F9F;\n"
"              }\n"
"             ")
        self.btnDeleteCustomer.setObjectName("btnDeleteCustomer")
        self.customerButtonLayout.addWidget(self.btnDeleteCustomer)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customerButtonLayout.addItem(spacerItem1)
        self.txtCustomerSearch = QtWidgets.QLineEdit(self.customerPage)
        self.txtCustomerSearch.setClearButtonEnabled(True)
        self.txtCustomerSearch.setStyleSheet("\n"
"              background-color: #F5F5F5;\n"
"              border: 1px solid #3F51B5;\n"
"              border-radius: 5px;\n"
"              padding: 5px;\n"
"              margin: 5px;\n"
"              color: #303F9F;\n"
"             ")
        self.txtCustomerSearch.setObjectName("txtCustomerSearch")
        self.customerButtonLayout.addWidget(self.txtCustomerSearch)
        self.customerLayout.addLayout(self.customerButtonLayout)
        self.stackedWidget_content.addWidget(self.customerPage)
        self.menuPage = QtWidgets.QWidget()
        self.menuPage.setObjectName("menuPage")
        self.menuLayout = QtWidgets.QVBoxLayout(self.menuPage)
        self.menuLayout.setObjectName("menuLayout")
        self.label_menuTitle = QtWidgets.QLabel(self.menuPage)
        self.label_menuTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_menuTitle.setStyleSheet("\n"
"            font-size: 24px;\n"
"            font-weight: bold;\n"
"            padding: 15px;\n"
"            color: #3F51B5;\n"
"            border-bottom: 2px solid #5C6BC0;\n"
"            margin-bottom: 10px;\n"
"           ")
        self.label_menuTitle.setObjectName("label_menuTitle")
        self.menuLayout.addWidget(self.label_menuTitle)
        self.menuTable = QtWidgets.QTableWidget(self.menuPage)
        self.menuTable.setColumnCount(5)
        self.menuTable.setRowCount(0)
        self.menuTable.setStyleSheet("\n"
"            background-color: #ECEFF1;\n"
"            alternate-background-color: #F5F5F5;\n"
"            selection-background-color: #283593;\n"
"            selection-color: #ECEFF1;\n"
"            border: 1px solid #303F9F;\n"
"            border-radius: 5px;\n"
"            margin: 5px;\n"
"           ")
        self.menuTable.setObjectName("menuTable")
        item = QtWidgets.QTableWidgetItem()
        self.menuTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.menuTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.menuTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.menuTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.menuTable.setHorizontalHeaderItem(4, item)
        self.menuLayout.addWidget(self.menuTable)
        self.menuButtonLayout = QtWidgets.QHBoxLayout()
        self.menuButtonLayout.setObjectName("menuButtonLayout")
        self.btnAddMenuItem = QtWidgets.QPushButton(self.menuPage)
        self.btnAddMenuItem.setIcon(icon5)
        self.btnAddMenuItem.setStyleSheet("\n"
"              QPushButton {\n"
"               background-color: #3F51B5;\n"
"               color: #ECEFF1;\n"
"               border-radius: 8px;\n"
"               padding: 8px 16px;\n"
"               font-weight: bold;\n"
"               border: 2px solid #3F51B5;\n"
"              }\n"
"\n"
"              QPushButton:hover {\n"
"               background-color: #5C6BC0;\n"
"               border: 2px solid #5C6BC0;\n"
"              }\n"
"\n"
"              QPushButton:pressed {\n"
"               background-color: #303F9F;\n"
"               border: 2px solid #303F9F;\n"
"              }\n"
"             ")
        self.btnAddMenuItem.setObjectName("btnAddMenuItem")
        self.menuButtonLayout.addWidget(self.btnAddMenuItem)
        self.btnEditMenuItem = QtWidgets.QPushButton(self.menuPage)
        self.btnEditMenuItem.setIcon(icon6)
        self.btnEditMenuItem.setStyleSheet("\n"
"              QPushButton {\n"
"               background-color: #3F51B5;\n"
"               color: #ECEFF1;\n"
"               border-radius: 8px;\n"
"               padding: 8px 16px;\n"
"               font-weight: bold;\n"
"               border: 2px solid #3F51B5;\n"
"              }\n"
"\n"
"              QPushButton:hover {\n"
"               background-color: #5C6BC0;\n"
"               border: 2px solid #5C6BC0;\n"
"              }\n"
"\n"
"              QPushButton:pressed {\n"
"               background-color: #303F9F;\n"
"               border: 2px solid #303F9F;\n"
"              }\n"
"             ")
        self.btnEditMenuItem.setObjectName("btnEditMenuItem")
        self.menuButtonLayout.addWidget(self.btnEditMenuItem)
        self.btnDeleteMenuItem = QtWidgets.QPushButton(self.menuPage)
        self.btnDeleteMenuItem.setIcon(icon7)
        self.btnDeleteMenuItem.setStyleSheet("\n"
"              QPushButton {\n"
"               background-color: #3F51B5;\n"
"               color: #ECEFF1;\n"
"               border-radius: 8px;\n"
"               padding: 8px 16px;\n"
"               font-weight: bold;\n"
"               border: 2px solid #3F51B5;\n"
"              }\n"
"\n"
"              QPushButton:hover {\n"
"               background-color: #5C6BC0;\n"
"               border: 2px solid #5C6BC0;\n"
"              }\n"
"\n"
"              QPushButton:pressed {\n"
"               background-color: #303F9F;\n"
"               border: 2px solid #303F9F;\n"
"              }\n"
"             ")
        self.btnDeleteMenuItem.setObjectName("btnDeleteMenuItem")
        self.menuButtonLayout.addWidget(self.btnDeleteMenuItem)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.menuButtonLayout.addItem(spacerItem2)
        self.cmbMenuCategory = QtWidgets.QComboBox(self.menuPage)
        self.cmbMenuCategory.setStyleSheet("\n"
"              background-color: #F5F5F5;\n"
"              border: 1px solid #3F51B5;\n"
"              border-radius: 5px;\n"
"              padding: 5px;\n"
"              margin: 5px;\n"
"              color: #303F9F;\n"
"             ")
        self.cmbMenuCategory.setObjectName("cmbMenuCategory")
        self.cmbMenuCategory.addItem("")
        self.cmbMenuCategory.addItem("")
        self.cmbMenuCategory.addItem("")
        self.cmbMenuCategory.addItem("")
        self.cmbMenuCategory.addItem("")
        self.menuButtonLayout.addWidget(self.cmbMenuCategory)
        self.menuLayout.addLayout(self.menuButtonLayout)
        self.stackedWidget_content.addWidget(self.menuPage)
        self.financePage = QtWidgets.QWidget()
        self.financePage.setObjectName("financePage")
        self.financeLayout = QtWidgets.QVBoxLayout(self.financePage)
        self.financeLayout.setObjectName("financeLayout")
        self.label_financeTitle = QtWidgets.QLabel(self.financePage)
        self.label_financeTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_financeTitle.setStyleSheet("\n"
"            font-size: 24px;\n"
"            font-weight: bold;\n"
"            padding: 15px;\n"
"            color: #3F51B5;\n"
"            border-bottom: 2px solid #5C6BC0;\n"
"            margin-bottom: 10px;\n"
"           ")
        self.label_financeTitle.setObjectName("label_financeTitle")
        self.financeLayout.addWidget(self.label_financeTitle)
        self.tabWidget_finance = QtWidgets.QTabWidget(self.financePage)
        self.tabWidget_finance.setStyleSheet("\n"
"            QTabWidget::pane { /* The tab widget frame */\n"
"             border: 1px solid #3F51B5;\n"
"             background: #ECEFF1;\n"
"             border-radius: 5px;\n"
"             margin: 5px;\n"
"            }\n"
"\n"
"            QTabWidget::tab-bar:top {\n"
"             alignment: center;\n"
"            }\n"
"\n"
"            QTabBar::tab {\n"
"             background: #5C6BC0;\n"
"             color: #ECEFF1;\n"
"             border: 1px solid #3F51B5;\n"
"             padding: 8px 15px;\n"
"             border-top-left-radius: 5px;\n"
"             border-top-right-radius: 5px;\n"
"             margin-right: 2px;\n"
"             font-weight: bold;\n"
"            }\n"
"\n"
"            QTabBar::tab:selected, QTabBar::tab:hover {\n"
"             background: #3F51B5;\n"
"             color: #ECEFF1;\n"
"            }\n"
"           ")
        self.tabWidget_finance.setObjectName("tabWidget_finance")
        self.tabIncome = QtWidgets.QWidget()
        self.tabIncome.setObjectName("tabIncome")
        self.incomeLayout = QtWidgets.QVBoxLayout(self.tabIncome)
        self.incomeLayout.setObjectName("incomeLayout")
        self.incomeTable = QtWidgets.QTableWidget(self.tabIncome)
        self.incomeTable.setStyleSheet("\n"
"                background-color: #ECEFF1;\n"
"                alternate-background-color: #F5F5F5;\n"
"                selection-background-color: #283593;\n"
"                selection-color: #ECEFF1;\n"
"                border: 1px solid #303F9F;\n"
"                border-radius: 5px;\n"
"                margin: 5px;\n"
"               ")
        self.incomeTable.setObjectName("incomeTable")
        self.incomeTable.setColumnCount(4)
        self.incomeTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.incomeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.incomeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.incomeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.incomeTable.setHorizontalHeaderItem(3, item)
        self.incomeLayout.addWidget(self.incomeTable)
        self.incomeButtonLayout = QtWidgets.QHBoxLayout()
        self.incomeButtonLayout.setObjectName("incomeButtonLayout")
        self.btnAddIncome = QtWidgets.QPushButton(self.tabIncome)
        self.btnAddIncome.setStyleSheet("\n"
"                  QPushButton {\n"
"                   background-color: #3F51B5;\n"
"                   color: #ECEFF1;\n"
"                   border-radius: 8px;\n"
"                   padding: 8px 16px;\n"
"                   font-weight: bold;\n"
"                   border: 2px solid #3F51B5;\n"
"                  }\n"
"\n"
"                  QPushButton:hover {\n"
"                   background-color: #5C6BC0;\n"
"                   border: 2px solid #5C6BC0;\n"
"                  }\n"
"\n"
"                  QPushButton:pressed {\n"
"                   background-color: #303F9F;\n"
"                   border: 2px solid #303F9F;\n"
"                  }\n"
"                 ")
        self.btnAddIncome.setObjectName("btnAddIncome")
        self.incomeButtonLayout.addWidget(self.btnAddIncome)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.incomeButtonLayout.addItem(spacerItem3)
        self.lblTotalIncome = QtWidgets.QLabel(self.tabIncome)
        self.lblTotalIncome.setStyleSheet("font-weight: bold; color: #4CAF50; color: #303F9F;")
        self.lblTotalIncome.setObjectName("lblTotalIncome")
        self.incomeButtonLayout.addWidget(self.lblTotalIncome)
        self.incomeLayout.addLayout(self.incomeButtonLayout)
        self.tabWidget_finance.addTab(self.tabIncome, "")
        self.tabExpenses = QtWidgets.QWidget()
        self.tabExpenses.setObjectName("tabExpenses")
        self.expensesLayout = QtWidgets.QVBoxLayout(self.tabExpenses)
        self.expensesLayout.setObjectName("expensesLayout")
        self.expensesTable = QtWidgets.QTableWidget(self.tabExpenses)
        self.expensesTable.setStyleSheet("\n"
"                background-color: #ECEFF1;\n"
"                alternate-background-color: #F5F5F5;\n"
"                selection-background-color: #283593;\n"
"                selection-color: #ECEFF1;\n"
"                border: 1px solid #303F9F;\n"
"                border-radius: 5px;\n"
"                margin: 5px;\n"
"               ")
        self.expensesTable.setObjectName("expensesTable")
        self.expensesTable.setColumnCount(4)
        self.expensesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.expensesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.expensesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.expensesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.expensesTable.setHorizontalHeaderItem(3, item)
        self.expensesLayout.addWidget(self.expensesTable)
        self.expensesButtonLayout = QtWidgets.QHBoxLayout()
        self.expensesButtonLayout.setObjectName("expensesButtonLayout")
        self.btnAddExpense = QtWidgets.QPushButton(self.tabExpenses)
        self.btnAddExpense.setStyleSheet("\n"
"                  QPushButton {\n"
"                   background-color: #3F51B5;\n"
"                   color: #ECEFF1;\n"
"                   border-radius: 8px;\n"
"                   padding: 8px 16px;\n"
"                   font-weight: bold;\n"
"                   border: 2px solid #3F51B5;\n"
"                  }\n"
"\n"
"                  QPushButton:hover {\n"
"                   background-color: #5C6BC0;\n"
"                   border: 2px solid #5C6BC0;\n"
"                  }\n"
"\n"
"                  QPushButton:pressed {\n"
"                   background-color: #303F9F;\n"
"                   border: 2px solid #303F9F;\n"
"                  }\n"
"                 ")
        self.btnAddExpense.setObjectName("btnAddExpense")
        self.expensesButtonLayout.addWidget(self.btnAddExpense)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.expensesButtonLayout.addItem(spacerItem4)
        self.lblTotalExpenses = QtWidgets.QLabel(self.tabExpenses)
        self.lblTotalExpenses.setStyleSheet("font-weight: bold; color: #F44336; color: #303F9F;")
        self.lblTotalExpenses.setObjectName("lblTotalExpenses")
        self.expensesButtonLayout.addWidget(self.lblTotalExpenses)
        self.expensesLayout.addLayout(self.expensesButtonLayout)
        self.tabWidget_finance.addTab(self.tabExpenses, "")
        self.financeLayout.addWidget(self.tabWidget_finance)
        self.netProfitLayout = QtWidgets.QHBoxLayout()
        self.netProfitLayout.setObjectName("netProfitLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.netProfitLayout.addItem(spacerItem5)
        self.lblNetProfit = QtWidgets.QLabel(self.financePage)
        self.lblNetProfit.setStyleSheet("font-size: 18px; font-weight: bold; color: #2196F3; color: #303F9F;")
        self.lblNetProfit.setObjectName("lblNetProfit")
        self.netProfitLayout.addWidget(self.lblNetProfit)
        self.financeLayout.addLayout(self.netProfitLayout)
        self.stackedWidget_content.addWidget(self.financePage)
        self.ordersPage = QtWidgets.QWidget()
        self.ordersPage.setObjectName("ordersPage")
        self.ordersLayout = QtWidgets.QVBoxLayout(self.ordersPage)
        self.ordersLayout.setObjectName("ordersLayout")
        self.label_ordersTitle = QtWidgets.QLabel(self.ordersPage)
        self.label_ordersTitle.setStyleSheet("\n"
"            font-size: 24px;\n"
"            font-weight: bold;\n"
"            padding: 15px;\n"
"            color: #3F51B5;\n"
"            border-bottom: 2px solid #5C6BC0;\n"
"            margin-bottom: 10px;\n"
"           ")
        self.label_ordersTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ordersTitle.setObjectName("label_ordersTitle")
        self.ordersLayout.addWidget(self.label_ordersTitle)
        self.ordersTable = QtWidgets.QTableWidget(self.ordersPage)
        self.ordersTable.setColumnCount(6)
        self.ordersTable.setRowCount(0)
        self.ordersTable.setStyleSheet("\n"
"            background-color: #ECEFF1;\n"
"            alternate-background-color: #F5F5F5;\n"
"            selection-background-color: #283593;\n"
"            selection-color: #ECEFF1;\n"
"            border: 1px solid #303F9F;\n"
"            border-radius: 5px;\n"
"            margin: 5px;\n"
"           ")
        self.ordersTable.setObjectName("ordersTable")
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(5, item)
        self.ordersLayout.addWidget(self.ordersTable)
        self.ordersButtonLayout = QtWidgets.QHBoxLayout()
        self.ordersButtonLayout.setObjectName("ordersButtonLayout")
        self.btnNewOrder = QtWidgets.QPushButton(self.ordersPage)
        self.btnNewOrder.setIcon(icon5)
        self.btnNewOrder.setStyleSheet("\n"
"              QPushButton {\n"
"               background-color: #3F51B5;\n"
"               color: #ECEFF1;\n"
"               border-radius: 8px;\n"
"               padding: 8px 16px;\n"
"               font-weight: bold;\n"
"               border: 2px solid #3F51B5;\n"
"              }\n"
"\n"
"              QPushButton:hover {\n"
"               background-color: #5C6BC0;\n"
"               border: 2px solid #5C6BC0;\n"
"              }\n"
"\n"
"              QPushButton:pressed {\n"
"               background-color: #303F9F;\n"
"               border: 2px solid #303F9F;\n"
"              }\n"
"             ")
        self.btnNewOrder.setObjectName("btnNewOrder")
        self.ordersButtonLayout.addWidget(self.btnNewOrder)
        self.btnEditOrder = QtWidgets.QPushButton(self.ordersPage)
        self.btnEditOrder.setIcon(icon6)
        self.btnEditOrder.setStyleSheet("\n"
"              QPushButton {\n"
"               background-color: #3F51B5;\n"
"               color: #ECEFF1;\n"
"               border-radius: 8px;\n"
"               padding: 8px 16px;\n"
"               font-weight: bold;\n"
"               border: 2px solid #3F51B5;\n"
"              }\n"
"\n"
"              QPushButton:hover {\n"
"               background-color: #5C6BC0;\n"
"               border: 2px solid #5C6BC0;\n"
"              }\n"
"\n"
"              QPushButton:pressed {\n"
"               background-color: #303F9F;\n"
"               border: 2px solid #303F9F;\n"
"              }\n"
"             ")
        self.btnEditOrder.setObjectName("btnEditOrder")
        self.ordersButtonLayout.addWidget(self.btnEditOrder)
        self.btnCancelOrder = QtWidgets.QPushButton(self.ordersPage)
        self.btnCancelOrder.setIcon(icon7)
        self.btnCancelOrder.setStyleSheet("\n"
"              QPushButton {\n"
"               background-color: #3F51B5;\n"
"               color: #ECEFF1;\n"
"               border-radius: 8px;\n"
"               padding: 8px 16px;\n"
"               font-weight: bold;\n"
"               border: 2px solid #3F51B5;\n"
"              }\n"
"\n"
"              QPushButton:hover {\n"
"               background-color: #5C6BC0;\n"
"               border: 2px solid #5C6BC0;\n"
"              }\n"
"\n"
"              QPushButton:pressed {\n"
"               background-color: #303F9F;\n"
"               border: 2px solid #303F9F;\n"
"              }\n"
"             ")
        self.btnCancelOrder.setObjectName("btnCancelOrder")
        self.ordersButtonLayout.addWidget(self.btnCancelOrder)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ordersButtonLayout.addItem(spacerItem6)
        self.cmbOrderStatusFilter = QtWidgets.QComboBox(self.ordersPage)
        self.cmbOrderStatusFilter.setStyleSheet("\n"
"              background-color: #F5F5F5;\n"
"              border: 1px solid #3F51B5;\n"
"              border-radius: 5px;\n"
"              padding: 5px;\n"
"              margin: 5px;\n"
"              color: #303F9F;\n"
"             ")
        self.cmbOrderStatusFilter.setObjectName("cmbOrderStatusFilter")
        self.cmbOrderStatusFilter.addItem("")
        self.cmbOrderStatusFilter.addItem("")
        self.cmbOrderStatusFilter.addItem("")
        self.cmbOrderStatusFilter.addItem("")
        self.cmbOrderStatusFilter.addItem("")
        self.ordersButtonLayout.addWidget(self.cmbOrderStatusFilter)
        self.ordersLayout.addLayout(self.ordersButtonLayout)
        self.stackedWidget_content.addWidget(self.ordersPage)
        self.mainLayout.addWidget(self.stackedWidget_content)
        AdminPanel.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AdminPanel)
        self.statusbar.setStyleSheet("\n"
"     background-color: #ECEFF1;\n"
"     color: #303F9F;\n"
"     padding: 3px;\n"
"     border-top: 2px solid #3F51B5;\n"
"     border-radius: 0;\n"
"    ")
        self.statusbar.setObjectName("statusbar")
        AdminPanel.setStatusBar(self.statusbar)

        self.retranslateUi(AdminPanel)
        self.listWidget_menu.currentRowChanged['int'].connect(self.stackedWidget_content.setCurrentIndex) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AdminPanel)

    def retranslateUi(self, AdminPanel):
        _translate = QtCore.QCoreApplication.translate
        AdminPanel.setWindowTitle(_translate("AdminPanel", "Restaurant Admin Panel"))
        self.label_restaurantName.setText(_translate("AdminPanel", "RESTAURANT"))
        __sortingEnabled = self.listWidget_menu.isSortingEnabled()
        self.listWidget_menu.setSortingEnabled(False)
        item = self.listWidget_menu.item(0)
        item.setText(_translate("AdminPanel", "Müşteri Yönetimi"))
        item = self.listWidget_menu.item(1)
        item.setText(_translate("AdminPanel", "Menü Yönetimi"))
        item = self.listWidget_menu.item(2)
        item.setText(_translate("AdminPanel", "Finansal İşlemler"))
        item = self.listWidget_menu.item(3)
        item.setText(_translate("AdminPanel", "Sipariş Yönetimi"))
        self.listWidget_menu.setSortingEnabled(__sortingEnabled)
        self.btnLogout.setText(_translate("AdminPanel", "Çıkış Yap"))
        self.label_customerTitle.setText(_translate("AdminPanel", "Müşteri Yönetimi"))
        self.customerTable.setSortingEnabled(True)
        item = self.customerTable.horizontalHeaderItem(0)
        item.setText(_translate("AdminPanel", "ID"))
        item = self.customerTable.horizontalHeaderItem(1)
        item.setText(_translate("AdminPanel", "Ad"))
        item = self.customerTable.horizontalHeaderItem(2)
        item.setText(_translate("AdminPanel", "Telefon"))
        item = self.customerTable.horizontalHeaderItem(3)
        item.setText(_translate("AdminPanel", "E-posta"))
        item = self.customerTable.horizontalHeaderItem(4)
        item.setText(_translate("AdminPanel", "Son Ziyaret"))
        self.btnAddCustomer.setText(_translate("AdminPanel", "Yeni Ekle"))
        self.btnEditCustomer.setText(_translate("AdminPanel", "Düzenle"))
        self.btnDeleteCustomer.setText(_translate("AdminPanel", "Sil"))
        self.txtCustomerSearch.setPlaceholderText(_translate("AdminPanel", "Müşteri ara..."))
        self.label_menuTitle.setText(_translate("AdminPanel", "Menü Yönetimi"))
        item = self.menuTable.horizontalHeaderItem(0)
        item.setText(_translate("AdminPanel", "ID"))
        item = self.menuTable.horizontalHeaderItem(1)
        item.setText(_translate("AdminPanel", "Ürün Adı"))
        item = self.menuTable.horizontalHeaderItem(2)
        item.setText(_translate("AdminPanel", "Kategori"))
        item = self.menuTable.horizontalHeaderItem(3)
        item.setText(_translate("AdminPanel", "Fiyat"))
        item = self.menuTable.horizontalHeaderItem(4)
        item.setText(_translate("AdminPanel", "Stok"))
        self.btnAddMenuItem.setText(_translate("AdminPanel", "Yeni Ürün"))
        self.btnEditMenuItem.setText(_translate("AdminPanel", "Düzenle"))
        self.btnDeleteMenuItem.setText(_translate("AdminPanel", "Sil"))
        self.cmbMenuCategory.setItemText(0, _translate("AdminPanel", "Tüm Kategoriler"))
        self.cmbMenuCategory.setItemText(1, _translate("AdminPanel", "Başlangıçlar"))
        self.cmbMenuCategory.setItemText(2, _translate("AdminPanel", "Ana Yemekler"))
        self.cmbMenuCategory.setItemText(3, _translate("AdminPanel", "İçecekler"))
        self.cmbMenuCategory.setItemText(4, _translate("AdminPanel", "Tatlılar"))
        self.label_financeTitle.setText(_translate("AdminPanel", "Finansal İşlemler"))
        item = self.incomeTable.horizontalHeaderItem(0)
        item.setText(_translate("AdminPanel", "Tarih"))
        item = self.incomeTable.horizontalHeaderItem(1)
        item.setText(_translate("AdminPanel", "Açıklama"))
        item = self.incomeTable.horizontalHeaderItem(2)
        item.setText(_translate("AdminPanel", "Miktar"))
        item = self.incomeTable.horizontalHeaderItem(3)
        item.setText(_translate("AdminPanel", "Kategori"))
        self.btnAddIncome.setText(_translate("AdminPanel", "Gelir Ekle"))
        self.lblTotalIncome.setText(_translate("AdminPanel", "Toplam Gelir: 0.00 TL"))
        self.tabWidget_finance.setTabText(self.tabWidget_finance.indexOf(self.tabIncome), _translate("AdminPanel", "Gelirler"))
        item = self.expensesTable.horizontalHeaderItem(0)
        item.setText(_translate("AdminPanel", "Tarih"))
        item = self.expensesTable.horizontalHeaderItem(1)
        item.setText(_translate("AdminPanel", "Açıklama"))
        item = self.expensesTable.horizontalHeaderItem(2)
        item.setText(_translate("AdminPanel", "Miktar"))
        item = self.expensesTable.horizontalHeaderItem(3)
        item.setText(_translate("AdminPanel", "Kategori"))
        self.btnAddExpense.setText(_translate("AdminPanel", "Gider Ekle"))
        self.lblTotalExpenses.setText(_translate("AdminPanel", "Toplam Gider: 0.00 TL"))
        self.tabWidget_finance.setTabText(self.tabWidget_finance.indexOf(self.tabExpenses), _translate("AdminPanel", "Giderler"))
        self.lblNetProfit.setText(_translate("AdminPanel", "Net Kâr: 0.00 TL"))
        self.label_ordersTitle.setText(_translate("AdminPanel", "Sipariş Yönetimi"))
        item = self.ordersTable.horizontalHeaderItem(0)
        item.setText(_translate("AdminPanel", "Sipariş ID"))
        item = self.ordersTable.horizontalHeaderItem(1)
        item.setText(_translate("AdminPanel", "Müşteri Adı"))
        item = self.ordersTable.horizontalHeaderItem(2)
        item.setText(_translate("AdminPanel", "Sipariş Tarihi"))
        item = self.ordersTable.horizontalHeaderItem(3)
        item.setText(_translate("AdminPanel", "Toplam Tutar"))
        item = self.ordersTable.horizontalHeaderItem(4)
        item.setText(_translate("AdminPanel", "Durum"))
        item = self.ordersTable.horizontalHeaderItem(5)
        item.setText(_translate("AdminPanel", "Detaylar"))
        self.btnNewOrder.setText(_translate("AdminPanel", "Yeni Sipariş"))
        self.btnEditOrder.setText(_translate("AdminPanel", "Düzenle"))
        self.btnCancelOrder.setText(_translate("AdminPanel", "İptal Et"))
        self.cmbOrderStatusFilter.setItemText(0, _translate("AdminPanel", "Tüm Siparişler"))
        self.cmbOrderStatusFilter.setItemText(1, _translate("AdminPanel", "Bekliyor"))
        self.cmbOrderStatusFilter.setItemText(2, _translate("AdminPanel", "Hazırlanıyor"))
        self.cmbOrderStatusFilter.setItemText(3, _translate("AdminPanel", "Teslim Edildi"))
        self.cmbOrderStatusFilter.setItemText(4, _translate("AdminPanel", "İptal Edildi"))

