# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pc\Desktop\KOD\örnek\Görsel Programlama Vize Proje\Restoran_Otomasyonu\örnek\a.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnaEkran(object):
    def setupUi(self, AnaEkran):
        AnaEkran.setObjectName("AnaEkran")
        AnaEkran.resize(1000, 700)
        AnaEkran.setStyleSheet("background-color: #FFE0B2;")
        self.centralwidget = QtWidgets.QWidget(AnaEkran)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.baslikLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.baslikLabel.setFont(font)
        self.baslikLabel.setStyleSheet("color: #2c3e50;\n"
"padding: 10px;")
        self.baslikLabel.setObjectName("baslikLabel")
        self.headerLayout.addWidget(self.baslikLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.profilButon = QtWidgets.QPushButton(self.centralwidget)
        self.profilButon.setMinimumSize(QtCore.QSize(100, 40))
        self.profilButon.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.profilButon.setFont(font)
        self.profilButon.setStyleSheet("QPushButton {\n"
"    background-color: #FF9800;\n"
"    color: black;\n"
"  border-radius: 15px;\n"
"  padding: 8px;\n"
"  border: none;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;}\n"
"QPushButton:pressed {\n"
"  background-color: #FB8C00;}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profilButon.setIcon(icon)
        self.profilButon.setObjectName("profilButon")
        self.headerLayout.addWidget(self.profilButon)
        self.verticalLayout.addLayout(self.headerLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("color: #e0e0e0;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: 1px solid #ddd;\n"
"  border-radius: 4px;\n"
"  padding: 4px;\n"
"  margin-top: 4px;\n"
"  background-color: #FFE0B2; /* Masalar sekmesi içeriği arka planı */\n"
"}\n"
"QTabBar::tab {\n"
"  background: #f1f1f1;\n"
"  border: 1px solid #ddd;\n"
"  padding: 8px 12px;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"  background: #FFA00;\n"
"  border-bottom-color: #FFA726;\n"
"}\n"
"QTabBar::tab:hover {\n"
"  background: #FFA726;\n"
"}\n"
"QTabBar::tab:over {\n"
"  background: #FB8C00;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.masalarTab = QtWidgets.QWidget()
        self.masalarTab.setStyleSheet("background-color: #FFE0B2;")
        self.masalarTab.setObjectName("masalarTab")
        self.gridLayout = QtWidgets.QGridLayout(self.masalarTab)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.masaButon1 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon1.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon1.setFont(font)
        self.masaButon1.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon1.setObjectName("masaButon1")
        self.gridLayout.addWidget(self.masaButon1, 0, 0, 1, 1)
        self.masaButon2 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon2.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon2.setFont(font)
        self.masaButon2.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon2.setObjectName("masaButon2")
        self.gridLayout.addWidget(self.masaButon2, 0, 1, 1, 1)
        self.masaButon3 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon3.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon3.setFont(font)
        self.masaButon3.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon3.setObjectName("masaButon3")
        self.gridLayout.addWidget(self.masaButon3, 0, 2, 1, 1)
        self.masaButon4 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon4.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon4.setFont(font)
        self.masaButon4.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon4.setObjectName("masaButon4")
        self.gridLayout.addWidget(self.masaButon4, 0, 3, 1, 1)
        self.masaButon5 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon5.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon5.setFont(font)
        self.masaButon5.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon5.setObjectName("masaButon5")
        self.gridLayout.addWidget(self.masaButon5, 1, 0, 1, 1)
        self.masaButon6 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon6.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon6.setFont(font)
        self.masaButon6.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon6.setObjectName("masaButon6")
        self.gridLayout.addWidget(self.masaButon6, 1, 1, 1, 1)
        self.masaButon7 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon7.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon7.setFont(font)
        self.masaButon7.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon7.setObjectName("masaButon7")
        self.gridLayout.addWidget(self.masaButon7, 1, 2, 1, 1)
        self.masaButon8 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon8.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon8.setFont(font)
        self.masaButon8.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon8.setObjectName("masaButon8")
        self.gridLayout.addWidget(self.masaButon8, 1, 3, 1, 1)
        self.masaButon9 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon9.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon9.setFont(font)
        self.masaButon9.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon9.setObjectName("masaButon9")
        self.gridLayout.addWidget(self.masaButon9, 2, 0, 1, 1)
        self.masaButon10 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon10.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon10.setFont(font)
        self.masaButon10.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon10.setObjectName("masaButon10")
        self.gridLayout.addWidget(self.masaButon10, 2, 1, 1, 1)
        self.masaButon11 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon11.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon11.setFont(font)
        self.masaButon11.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon11.setObjectName("masaButon11")
        self.gridLayout.addWidget(self.masaButon11, 2, 2, 1, 1)
        self.masaButon12 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon12.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon12.setFont(font)
        self.masaButon12.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon12.setObjectName("masaButon12")
        self.gridLayout.addWidget(self.masaButon12, 2, 3, 1, 1)
        self.masaButon13 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon13.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon13.setFont(font)
        self.masaButon13.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon13.setObjectName("masaButon13")
        self.gridLayout.addWidget(self.masaButon13, 3, 0, 1, 1)
        self.masaButon14 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon14.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon14.setFont(font)
        self.masaButon14.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon14.setObjectName("masaButon14")
        self.gridLayout.addWidget(self.masaButon14, 3, 1, 1, 1)
        self.masaButon15 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon15.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon15.setFont(font)
        self.masaButon15.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon15.setObjectName("masaButon15")
        self.gridLayout.addWidget(self.masaButon15, 3, 2, 1, 1)
        self.masaButon16 = QtWidgets.QPushButton(self.masalarTab)
        self.masaButon16.setMinimumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.masaButon16.setFont(font)
        self.masaButon16.setStyleSheet("QPushButton {\n"
"  background-color: #FF9800;\n"
"  color: white;\n"
"  border-radius: 15px;\n"
"  padding: 8px 16px;\n"
"  font-weight: bold;\n"
"  border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"  background-color: #FB8C00;\n"
"  border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"  background-color: #F57C00;\n"
"  border: 2px solid #F57C00;\n"
"}")
        self.masaButon16.setObjectName("masaButon16")
        self.gridLayout.addWidget(self.masaButon16, 3, 3, 1, 1)
        self.tabWidget.addTab(self.masalarTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        AnaEkran.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnaEkran)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        AnaEkran.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnaEkran)
        self.statusbar.setStyleSheet("color: #7f8c8d;")
        self.statusbar.setObjectName("statusbar")
        AnaEkran.setStatusBar(self.statusbar)

        self.retranslateUi(AnaEkran)
        QtCore.QMetaObject.connectSlotsByName(AnaEkran)

    def retranslateUi(self, AnaEkran):
        _translate = QtCore.QCoreApplication.translate
        AnaEkran.setWindowTitle(_translate("AnaEkran", "🍽️Restoran Otomasyonu"))
        self.baslikLabel.setText(_translate("AnaEkran", "Restoranımıza Hoş Geldiniz"))
        self.profilButon.setText(_translate("AnaEkran", "👨‍🍳"))
        self.masaButon1.setText(_translate("AnaEkran", "Masa 1 (Boş)"))
        self.masaButon2.setText(_translate("AnaEkran", "Masa 2 (Boş)"))
        self.masaButon3.setText(_translate("AnaEkran", "Masa 3 (Boş)"))
        self.masaButon4.setText(_translate("AnaEkran", "Masa 4 (Boş)"))
        self.masaButon5.setText(_translate("AnaEkran", "Masa 5 (Boş)"))
        self.masaButon6.setText(_translate("AnaEkran", "Masa 6 (Boş)"))
        self.masaButon7.setText(_translate("AnaEkran", "Masa 7 (Boş)"))
        self.masaButon8.setText(_translate("AnaEkran", "Masa 8 (Boş)"))
        self.masaButon9.setText(_translate("AnaEkran", "Masa 9 (Boş)"))
        self.masaButon10.setText(_translate("AnaEkran", "Masa 10 (Boş)"))
        self.masaButon11.setText(_translate("AnaEkran", "Masa 11 (Boş)"))
        self.masaButon12.setText(_translate("AnaEkran", "Masa 12 (Boş)"))
        self.masaButon13.setText(_translate("AnaEkran", "Masa 13 (Boş)"))
        self.masaButon14.setText(_translate("AnaEkran", "Masa 14 (Boş)"))
        self.masaButon15.setText(_translate("AnaEkran", "Masa 15 (Boş)"))
        self.masaButon16.setText(_translate("AnaEkran", "Masa 16 (Boş)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.masalarTab), _translate("AnaEkran", "🏠 Masalar"))
