# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pc\Desktop\KOD\örnek\Görsel Programlama Vize Proje\Restoran_Otomasyonu\örnek\Kart.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KartBilgisiEkrani(object):
    def setupUi(self, KartBilgisiEkrani):
        KartBilgisiEkrani.setObjectName("KartBilgisiEkrani")
        KartBilgisiEkrani.resize(400, 400)
        KartBilgisiEkrani.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #FFE0B2, stop:1 #FFCC80);\n"
"border-radius: 15px;\n"
"border: 2px solid #FFA726;")
        self.verticalLayout = QtWidgets.QVBoxLayout(KartBilgisiEkrani)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_toplam = QtWidgets.QLabel(KartBilgisiEkrani)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_toplam.setFont(font)
        self.label_toplam.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom: 2px solid #FFA000;\n"
"color: #5D4037;\n"
"padding-bottom: 7px;\n"
"border-radius: 4px;")
        self.label_toplam.setAlignment(QtCore.Qt.AlignCenter)
        self.label_toplam.setObjectName("label_toplam")
        self.verticalLayout.addWidget(self.label_toplam)
        self.label_kart_ustu = QtWidgets.QLabel(KartBilgisiEkrani)
        self.label_kart_ustu.setStyleSheet("font-weight: bold;\n"
"color: #5D4037;\n"
"margin-top: 10px;")
        self.label_kart_ustu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kart_ustu.setObjectName("label_kart_ustu")
        self.verticalLayout.addWidget(self.label_kart_ustu)
        self.kart_numarasi = QtWidgets.QLineEdit(KartBilgisiEkrani)
        self.kart_numarasi.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n"
"border: 1px solid #FFA726;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"margin: 5px;")
        self.kart_numarasi.setObjectName("kart_numarasi")
        self.verticalLayout.addWidget(self.kart_numarasi)
        self.kart_adi = QtWidgets.QLineEdit(KartBilgisiEkrani)
        self.kart_adi.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n"
"border: 1px solid #FFA726;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"margin: 5px;")
        self.kart_adi.setObjectName("kart_adi")
        self.verticalLayout.addWidget(self.kart_adi)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.skt_ay = QtWidgets.QLineEdit(KartBilgisiEkrani)
        self.skt_ay.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n"
"border: 1px solid #FFA726;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"margin: 5px;")
        self.skt_ay.setMaxLength(2)
        self.skt_ay.setObjectName("skt_ay")
        self.horizontalLayout.addWidget(self.skt_ay)
        self.skt_yil = QtWidgets.QLineEdit(KartBilgisiEkrani)
        self.skt_yil.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n"
"border: 1px solid #FFA726;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"margin: 5px;")
        self.skt_yil.setMaxLength(2)
        self.skt_yil.setObjectName("skt_yil")
        self.horizontalLayout.addWidget(self.skt_yil)
        self.cvv_kodu = QtWidgets.QLineEdit(KartBilgisiEkrani)
        self.cvv_kodu.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n"
"border: 1px solid #FFA726;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"margin: 5px;")
        self.cvv_kodu.setMaxLength(3)
        self.cvv_kodu.setEchoMode(QtWidgets.QLineEdit.Password)
        self.cvv_kodu.setObjectName("cvv_kodu")
        self.horizontalLayout.addWidget(self.cvv_kodu)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.odeme_btn = QtWidgets.QPushButton(KartBilgisiEkrani)
        self.odeme_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FF9800;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #FF9800;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FB8C00;\n"
"    border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F57C00;\n"
"    border: 2px solid #F57C00;\n"
"}")
        self.odeme_btn.setObjectName("odeme_btn")
        self.verticalLayout.addWidget(self.odeme_btn)

        self.retranslateUi(KartBilgisiEkrani)
        QtCore.QMetaObject.connectSlotsByName(KartBilgisiEkrani)

    def retranslateUi(self, KartBilgisiEkrani):
        _translate = QtCore.QCoreApplication.translate
        KartBilgisiEkrani.setWindowTitle(_translate("KartBilgisiEkrani", "💳 Kart Bilgileri"))
        self.label_toplam.setText(_translate("KartBilgisiEkrani", "Toplam Tutar: {toplam_tutar} TL"))
        self.label_kart_ustu.setText(_translate("KartBilgisiEkrani", "Kart Üzerindeki Bilgiler"))
        self.kart_numarasi.setPlaceholderText(_translate("KartBilgisiEkrani", "Kart Numarası (16 Hane)"))
        self.kart_adi.setPlaceholderText(_translate("KartBilgisiEkrani", "Kart Üzerindeki Ad Soyad"))
        self.skt_ay.setPlaceholderText(_translate("KartBilgisiEkrani", "AA (Ay)"))
        self.skt_yil.setPlaceholderText(_translate("KartBilgisiEkrani", "YY (Yıl)"))
        self.cvv_kodu.setPlaceholderText(_translate("KartBilgisiEkrani", "CVV (3 Hane)"))
        self.odeme_btn.setText(_translate("KartBilgisiEkrani", "Ödemeyi Tamamla"))
