# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pc\Desktop\KOD\Restoran Otomasyon\ui\MasaPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MasaSayfasi(object):
    def setupUi(self, MasaSayfasi):
        MasaSayfasi.setObjectName("MasaSayfasi")
        MasaSayfasi.resize(500, 400)
        MasaSayfasi.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #FFE0B2, stop:1 #FFCC80);\n"
"border-radius: 15px;\n"
"border: 2px solid #FFA726;")
        self.verticalLayout = QtWidgets.QVBoxLayout(MasaSayfasi)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_menu = QtWidgets.QVBoxLayout()
        self.verticalLayout_menu.setObjectName("verticalLayout_menu")
        self.label_kategori = QtWidgets.QLabel(MasaSayfasi)
        self.label_kategori.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom: 2px solid #FFA000;\n"
"color: #5D4037;\n"
"padding-bottom: 7px;\n"
"border-radius: 4px;")
        self.label_kategori.setObjectName("label_kategori")
        self.verticalLayout_menu.addWidget(self.label_kategori)
        self.kategori_secim = QtWidgets.QComboBox(MasaSayfasi)
        self.kategori_secim.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom: 2px solid #FFA000;\n"
"color: #5D4037;\n"
"padding-bottom: 7px;\n"
"border-radius: 4px;")
        self.kategori_secim.setObjectName("kategori_secim")
        self.kategori_secim.clear()
        self.verticalLayout_menu.addWidget(self.kategori_secim)
        self.label_urun = QtWidgets.QLabel(MasaSayfasi)
        self.label_urun.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom: 2px solid #FFA000;\n"
"color: #5D4037;\n"
"padding-bottom: 7px;\n"
"border-radius: 4px;")
        self.label_urun.setObjectName("label_urun")
        self.verticalLayout_menu.addWidget(self.label_urun)
        self.urun_secim = QtWidgets.QComboBox(MasaSayfasi)
        self.urun_secim.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom: 2px solid #FFA000;\n"
"color: #5D4037;\n"
"padding-bottom: 7px;\n"
"border-radius: 4px;")
        self.urun_secim.setObjectName("urun_secim")
        self.verticalLayout_menu.addWidget(self.urun_secim)
        self.verticalLayout.addLayout(self.verticalLayout_menu)
        self.verticalLayout_siparis = QtWidgets.QVBoxLayout()
        self.verticalLayout_siparis.setObjectName("verticalLayout_siparis")
        self.label_siparisler = QtWidgets.QLabel(MasaSayfasi)
        self.label_siparisler.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom: 2px solid #FFA000;\n"
"color: #5D4037;\n"
"padding-bottom: 7px;\n"
"border-radius: 4px;")
        self.label_siparisler.setObjectName("label_siparisler")
        self.verticalLayout_siparis.addWidget(self.label_siparisler)
        self.siparis_listesi = QtWidgets.QListWidget(MasaSayfasi)
        self.siparis_listesi.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom: 2px solid #FFA000;\n"
"color: #5D4037;\n"
"padding-bottom: 7px;\n"
"border-radius: 4px;")
        self.siparis_listesi.setObjectName("siparis_listesi")
        self.verticalLayout_siparis.addWidget(self.siparis_listesi)
        self.verticalLayout.addLayout(self.verticalLayout_siparis)
        self.verticalLayout_butonlar = QtWidgets.QVBoxLayout()
        self.verticalLayout_butonlar.setObjectName("verticalLayout_butonlar")
        self.ekle_btn = QtWidgets.QPushButton(MasaSayfasi)
        self.ekle_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FF9800;\n"
"    color: black\n"
";\n"
"    border-radius: 15px;\n"
"    padding: 4px 8px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #FF9800;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FB8C00;\n"
"    border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F57C00;\n"
"    border: 2px solid #F57C00;\n"
"}")
        self.ekle_btn.setObjectName("ekle_btn")
        self.verticalLayout_butonlar.addWidget(self.ekle_btn)
        self.odeme_btn = QtWidgets.QPushButton(MasaSayfasi)
        self.odeme_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FF9800;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"    padding: 4px 8px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"    background-color: #FB8C00;\n"
"    border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"    background-color: #F57C00;\n"
"    border: 2px solid #F57C00;\n"
"}")
        self.odeme_btn.setObjectName("odeme_btn")
        self.verticalLayout_butonlar.addWidget(self.odeme_btn)
        self.verticalLayout.addLayout(self.verticalLayout_butonlar)

        self.retranslateUi(MasaSayfasi)
        QtCore.QMetaObject.connectSlotsByName(MasaSayfasi)

    def retranslateUi(self, MasaSayfasi):
        _translate = QtCore.QCoreApplication.translate
        MasaSayfasi.setWindowTitle(_translate("MasaSayfasi", "Masa {masa_numarasi} Sipariş Ekranı"))
        self.label_kategori.setText(_translate("MasaSayfasi", "Kategori Seçin:"))
        self.label_urun.setText(_translate("MasaSayfasi", "Ürün Seçin:"))
        self.label_siparisler.setText(_translate("MasaSayfasi", "Siparişler:"))
        self.ekle_btn.setText(_translate("MasaSayfasi", "➕ Sipariş Ekle"))
        self.odeme_btn.setText(_translate("MasaSayfasi", "💰 Ödeme Yap"))
