# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pc\Desktop\KOD\Restoran Otomasyon\ui\OdemePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OdemeSecimEkrani(object):
    def setupUi(self, OdemeSecimEkrani):
        OdemeSecimEkrani.setObjectName("OdemeSecimEkrani")
        OdemeSecimEkrani.resize(300, 120)  # Boyutu küçülttük
        OdemeSecimEkrani.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #FFE0B2, stop:1 #FFCC80);\n"
"border-radius: 15px;\n"
"border: 2px solid #FFA726;")
        self.verticalLayout = QtWidgets.QVBoxLayout(OdemeSecimEkrani)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_toplam = QtWidgets.QLabel(OdemeSecimEkrani)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_toplam.setFont(font)
        self.label_toplam.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom: 2px solid #FFA000;\n"
"color: #5D4037;\n"
"padding-bottom: 7px;\n"
"border-radius: 4px;")
        self.label_toplam.setAlignment(QtCore.Qt.AlignCenter)
        self.label_toplam.setObjectName("label_toplam")
        self.verticalLayout.addWidget(self.label_toplam)
        self.kart_btn = QtWidgets.QPushButton(OdemeSecimEkrani)
        self.kart_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FF9800;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #FF9800;\n"
"}\n"
"\n"
"/* Hover efekti (üzerine gelindiğinde) */\n"
"QPushButton:hover {\n"
"    background-color: #FB8C00;\n"
"    border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"/* Basılı durum efekti */\n"
"QPushButton:pressed {\n"
"    background-color: #F57C00;\n"
"    border: 2px solid #F57C00;\n"
"}")
        self.kart_btn.setObjectName("kart_btn")
        self.verticalLayout.addWidget(self.kart_btn)

        self.retranslateUi(OdemeSecimEkrani)
        QtCore.QMetaObject.connectSlotsByName(OdemeSecimEkrani)

    def retranslateUi(self, OdemeSecimEkrani):
        _translate = QtCore.QCoreApplication.translate
        OdemeSecimEkrani.setWindowTitle(_translate("OdemeSecimEkrani", "💳 Ödeme Seçimi"))
        self.label_toplam.setText(_translate("OdemeSecimEkrani", "Toplam Tutar: {toplam_tutar} TL"))
        self.kart_btn.setText(_translate("OdemeSecimEkrani", "💳 Kart ile Ödeme"))