# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pc\Desktop\KOD\örnek\Görsel Programlama Vize Proje\Restoran_Otomasyonu\örnek\a.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfilSayfasi(object):
    def setupUi(self, ProfilSayfasi):
        ProfilSayfasi.setObjectName("ProfilSayfasi")
        ProfilSayfasi.resize(400, 500)
        ProfilSayfasi.setStyleSheet("background-color: #FFE0B2;")
        self.verticalLayout = QtWidgets.QVBoxLayout(ProfilSayfasi)
        self.verticalLayout.setObjectName("verticalLayout")
        self.baslikLabel = QtWidgets.QLabel(ProfilSayfasi)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.baslikLabel.setFont(font)
        self.baslikLabel.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom: 2px solid #FFA000;\n"
"color: #5D4037;\n"
"padding-bottom: 7px;\n"
"border-radius: 4px;")
        self.baslikLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.baslikLabel.setObjectName("baslikLabel")
        self.verticalLayout.addWidget(self.baslikLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(20, 20, 20, 10)
        self.formLayout.setObjectName("formLayout")
        self.kullaniciAdiLabel = QtWidgets.QLabel(ProfilSayfasi)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.kullaniciAdiLabel.setFont(font)
        self.kullaniciAdiLabel.setObjectName("kullaniciAdiLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.kullaniciAdiLabel)
        self.kullaniciAdiLineEdit = QtWidgets.QLineEdit(ProfilSayfasi)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.kullaniciAdiLineEdit.setFont(font)
        self.kullaniciAdiLineEdit.setStyleSheet("background-color: white;\n"
"border: 1px solid #ced4da;\n"
"border-radius: 4px;\n"
"padding: 6px;")
        self.kullaniciAdiLineEdit.setObjectName("kullaniciAdiLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kullaniciAdiLineEdit)
        self.sifreLabel = QtWidgets.QLabel(ProfilSayfasi)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.sifreLabel.setFont(font)
        self.sifreLabel.setObjectName("sifreLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sifreLabel)
        self.sifreLineEdit = QtWidgets.QLineEdit(ProfilSayfasi)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.sifreLineEdit.setFont(font)
        self.sifreLineEdit.setStyleSheet("background-color: white;\n"
"border: 1px solid #ced4da;\n"
"border-radius: 4px;\n"
"padding: 6px;")
        self.sifreLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sifreLineEdit.setObjectName("sifreLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sifreLineEdit)
        self.epostaLabel = QtWidgets.QLabel(ProfilSayfasi)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.epostaLabel.setFont(font)
        self.epostaLabel.setObjectName("epostaLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.epostaLabel)
        self.epostaLineEdit = QtWidgets.QLineEdit(ProfilSayfasi)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.epostaLineEdit.setFont(font)
        self.epostaLineEdit.setStyleSheet("background-color: white;\n"
"border: 1px solid #ced4da;\n"
"border-radius: 4px;\n"
"padding: 6px;")
        self.epostaLineEdit.setObjectName("epostaLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.epostaLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.guncelleButon = QtWidgets.QPushButton(ProfilSayfasi)
        self.guncelleButon.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.guncelleButon.setFont(font)
        self.guncelleButon.setStyleSheet("QPushButton {\n"
"    background-color: #FF9800;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #FF9800;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FB8C00;\n"
"    border: 2px solid #FB8C00;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F57C00;\n"
"    border: 2px solid #F57C00;\n"
"}")
        self.guncelleButon.setObjectName("guncelleButon")
        self.verticalLayout.addWidget(self.guncelleButon)
        self.gecmisGroupBox = QtWidgets.QGroupBox(ProfilSayfasi)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gecmisGroupBox.setFont(font)
        self.gecmisGroupBox.setStyleSheet("margin-top: 20px;\n"
"border: 1px solid #e0e0e0;\n"
"border-radius: 5px;\n"
"padding: 10px;")
        self.gecmisGroupBox.setObjectName("gecmisGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gecmisGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gecmisTextEdit = QtWidgets.QTextEdit(self.gecmisGroupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.gecmisTextEdit.setFont(font)
        self.gecmisTextEdit.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n"
"border: 1px solid #FFA726;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"")
        self.gecmisTextEdit.setReadOnly(True)
        self.gecmisTextEdit.setObjectName("gecmisTextEdit")
        self.verticalLayout_2.addWidget(self.gecmisTextEdit)
        self.verticalLayout.addWidget(self.gecmisGroupBox)

        self.retranslateUi(ProfilSayfasi)
        QtCore.QMetaObject.connectSlotsByName(ProfilSayfasi)

    def retranslateUi(self, ProfilSayfasi):
        _translate = QtCore.QCoreApplication.translate
        ProfilSayfasi.setWindowTitle(_translate("ProfilSayfasi", "Profil"))
        self.baslikLabel.setText(_translate("ProfilSayfasi", "Kullanıcı Profili"))
        self.kullaniciAdiLabel.setText(_translate("ProfilSayfasi", "Kullanıcı Adı:"))
        self.sifreLabel.setText(_translate("ProfilSayfasi", "Şifre:"))
        self.epostaLabel.setText(_translate("ProfilSayfasi", "E-posta:"))
        self.guncelleButon.setText(_translate("ProfilSayfasi", "Güncelle"))
        self.gecmisGroupBox.setTitle(_translate("ProfilSayfasi", "Geçmiş"))
        self.gecmisTextEdit.setPlaceholderText(_translate("ProfilSayfasi", "Burada geçmiş işlemleriniz listelenecektir."))
